# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

import java.util.Scanner;

public class BookingSystem {
    public static void main(String[] args) {
        try {
            Scanner scanner = new Scanner(System.in);

            System.out.println("Welcome to the Booking System!");
            System.out.print("Enter your name: ");
            String userName = scanner.nextLine();

            System.out.print("Enter the service you want to book: ");
            String service = scanner.nextLine();

            System.out.print("Enter the date of booking (DD/MM/YYYY): ");
            String date = scanner.nextLine();

            System.out.println("Booking confirmed for " + userName + " for " + service + " on " + date);

            scanner.close();
        } catch (Exception e) {
            System.out.println("An error occurred. Please try again.");
            e.printStackTrace();
        }
    }
}

